### ISSUE TITLE
Release Resources

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#122]
NOTE: Original description below. This has been updated to reflect the task to "release a book package". The requirements are detailed [here](https://docs.google.com/document/d/17R1rTvdwuYtINzfoCdd1SThyuk7zIQZYMVsHezQkX0g/edit#heading=h.lzic74fjjo5s)

The same information is posted below.

The goal here is to assist the user in releasing resources for use in our tools.   Work should be done to avoid technical or git language in order to communicate to the user in terms they would think of.

**Comment by mandolyte** [comment]
# Proposed gatewayAdmin user workflow 
## Goal
**Simplicity**
Latest released commit will have *only* approved content and the manifest in that commit will *only* point to those. Note: this prevents translators from selecting content to translate that isn’t approved. Since the latest release could be tagged as a “pre-release”, it will still be possible to do a “risk-release” of some content in order to allow users early access (for example, perhaps the first three chapters of a book are good to go, but not the remainder of the book).
Release notes will be available to describe any nuances, such as any caveats in a pre-release.
## Notes
**Simplicity**: This goal will be supported by allowing the admin to select only the new books to be released (or updated). These will be “added” or “appended” to the latest release. The latest release could be either in a production or a pre-release state - so care should be taken.

**Prerequisites**: Before this workflow is used the first time, a manual release must be done to create a starting point that contains only the approved content and a matching manifest.

**translationCore**: tC is an offline tool which uploads new/updated content to a personal repository. The description below does not address how this content ends up in the master branch of the correct resource repository.
# Workflow
## Initial State
First, the prerequisites above must be completed. At this point, the initial state will be:

- A master branch containing all content, both released and work in progress.
- A manifest in the master branch that points to all the files in the branch.
- A latest release that may be either production or a pre-release.
- The latest release commit will only have the files that are approved to be released.
- The latest release will have release notes with any details on what is new and, if a pre-release, any cautions.
- The latest release will have a manifest that points only to the files in that release commit.

## UI/X Design
**Goal**: Allow multiple book packages to be released at the same time.

At a high level, take the existing [release repo page](https://gateway-admin.netlify.app/releaseRepo) and make it into a release book package page.This requires the following cosmetic changes:
Change the wording on the link on the navigation bar and the page itself
Replace the “select resource” area with a two part interface to select books and to select resources

**Assumption**: all resources selected apply to all the books selected.

### Book Package Selection
The Book Package (BP) consists of two distinct inputs: books (including OBS) and resources.

Since the book selection requires 67 possible inputs, I propose something like what is used by the [Book Package Flow app](https://unfoldingword.github.io/book-package-app/). Because this takes a lot of space, we should use a tabbed interface or a tree component to expand and contract as needed.
The resource selection is dependent on the book selection, specifically:
If the use selects OBS, then the resources that are selectable are:

- Open Bible Stories (OBS)	
- OBS Translation Notes	
- OBS Translation Word List	
- OBS Translation Questions	
- OBS Translation Academy (same as scripture)
- OBS Translation Words (same as scripture)
- OBS Study Notes	
- OBS Study Questions

Note that OBS does not include LT or ST. And OBS repos follow different naming conventions to avoid conflict with Scripture resource naming conventions.

If the user selects scripture books only, then the selectable resources are:

- Literal Translation	
- Simplified Translation	
- Translation Notes	
- Translation Word List	
- Translation Words	
- Translation Academy	
- Translation Questions	
- Study Questions	
- Study Notes

Note that Scripture resources do not include the OBS text itself. And Scripture resource repo names follow different naming conventions from OBS equivalents.

If the user selects both OBS and any Scriptures, then the selectable resources will include the OBS in addition to the normal Scripture resources.

### Other UI Elements
#### Release Type
This will remain unchanged, offering either Production or Pre-release.

#### Release Version
This will be removed and handled by the gA automatically. It will be a simple integer increment with a “v” prefixed.

#### Release Name
This will remain unchanged, allowing the admin to provide a short title for the release. It will be used for all released resources.

#### Release Notes
This will remain unchanged, allowing the admin to supply a single set of release notes covering all resources. As mentioned above, if this is a pre-release, then the notes should cover the caveats.

## Application Actions
Once the admin clicks to release the book package, the application must, per resource:

- Create a branch from the latest release commit
- Add or update the content in that branch
- Compute the incremented version to use
- Update the manifest so that:
   - Only the files in the release are included in the projects section
   - The version in the manifest must match the release version
   - Create the release with new version, provided release notes, release name, and release state (production or pre-release)

## What can go wrong? 

**Condition**: The resource does not exist for the books. This is already known to gA. Check and verify. Or prevent the condition by disabling any non-existent resources.

**Condition**: One of the books does not exist in one or more of the resources selected. Ignore, perhaps show a “log” of warnings after work is completed.

**Condition**: Work is interrupted, failing for some reason. Discontinue processing and show a warning. Unlike a database, DCS does not have “transactions” and we cannot rollback work done. We can only abort and try to show the user what remains to be done so they can pick up the pieces afterwards.

**Condition**: Admin releases corrupted files. Since gA is able to run the validations, we might check and verify that in this session the admin has run the validations on the books selected. If not, we could prevent the release.

## Other Considerations

### Determining the Book Package

Given an organization, a language, and a book, then the book package for that book is:

- The set of all latest releases (production or pre-release) of the following resources for the given book:
- LT ([link](https://git.door43.org/unfoldingWord/en_ult/src/commit/c4518859b88cb67d92068ff76c7d85692d5cb168/08-RUT.usfm))
- ST ([link](https://git.door43.org/unfoldingWord/en_ust/src/commit/6ace37f492658765e9848a2ef58455f4ac8bdc2a/08-RUT.usfm))
- TN ([link](https://git.door43.org/unfoldingWord/en_tn/src/commit/5e3a7c90081f9455697c7332736f045a49eb5db8/en_tn_08-RUT.tsv))
- TWL ([link](https://git.door43.org/unfoldingWord/en_twl/src/commit/67de21f3b37b0a2197044b9ab124cfaef2549c9d/twl_RUT.tsv))
- TQ ([link](https://git.door43.org/unfoldingWord/en_tq/src/commit/0161929be86554f27faccd8b5c0786110cc3aef9/tq_RUT.tsv))
- SQ (does not exist yet)
- SN (does not exist yet)
- Plus the extant TW articles referenced in the TWL and the extant TA articles referenced in the TN.

The links provided alongside each resource is the actual file as of this writing for the book of Ruth for unfoldingWord and English.

These determinations could be done in code (perhaps a reusable library) or might be implemented as a new endpoint in Catalog Next.

### Solving for the “Translation From” Problem
This problem is where a translator needs to “stick” to a released version from which to translate until the work is completed. This is needed to clearly separate and not confuse updates from multiple versions of the resource. And also, that the translation be evaluated by a reviewer against the correct version.

This problem is technically a concern of the translation application and should be solved there. It is not properly a concern of the gatewayAdmin application.

**Comment by mandolyte** [comment]
# More on versioning
@Birch#5096 looks like the Russian team is also using the multi-part version scheme (see picture, link above). Altho, their latest version of ru_tn is v52 (should be v52.1). If gA needs to support this, then we need to prompt for the parts (up to three parts). Verifying that entered data is correct will be tricky.

- the first part "usually" refers to the English (uW) release. "usually" means we can't assume that. Perhaps we should ask what the source is?
- the second part is easier... if the first part is the same as the current release (if any), then it should 1 version higher. Otherwise, it should be "1".
- the third part should only be entered by an OL, so if not a gateway language, we could hide this one. Conceptually similar to preceding. If the first two parts the same, then +1; else should be "1".
-

**Comment by mandolyte** [comment]
# Testing 2022-10-03

Goal: test release of OBS and Mixed OBS/Scripture resources

## Setup

None required. The refresh over the weekend reset QA to match current production.

## Test 1

Using organization `es-419_gl` and language `es-419`, release:

- Books: OBS and Titus
- Resource: Translation Notes

**Results**

- Worked perfectly.
- I have concerns about updating manifest in the master branch and wrote up issue #139
