### ISSUE TITLE
Repo Initialization; Status and Actions

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-admin#40]
Below are the possible statuses and proposed actions for each.

### REPO_NOT_FOUND = 'Repo not found'
Action is to create the repo. **DONE**

### FILE_NOT_FOUND = 'File not found'
No action required. Perhaps indicate that tc-create should be used to create the file.

### BOOK_NOT_IN_MANIFEST = 'Book not in manifest'
Action is to add the selected book to the manifest.

### NO_FILES_IN_REPO = "No files in repo"
Action is to create the manifest with the current book package added to the manifest.

### NO_MANIFEST_FOUND = "No manifest found"
Action is to create the manifest with the current book package added to the manifest.

### UNABLE_TO_DECODE_MANIFEST = "Unable to decode manifest"
This will happen when the manifest is not syntactically correct YAML (or not even a YAML file at all). Proposed action is to request that file be correct manually or deleted.

### UNABLE_TO_RETRIEVE_MANIFEST = "Unable to retrieve manifest"
This is likely a network or access error. Propose that the admin be informed to try again later or fix possible access permissions.

### "xxx missing"
This status is shown for TW and TA resources (Bible and OBS). Proposed action to show the user the items that are missing.

### "No TWL repo" and "See TWL error"
These two statuses are possible for the TW resource. Since the TW resources for a book cannot be determined with the TWL, these are possible outcomes. There is no action to be taken for TW, since the action must be taken for TWL instead. Propose that a fuller explanation be given as the action.

### "No TN repo" and "See TN error"
This is same as preceding but for the TA resource.

**Comment by birchamp** [comment]
@mandolyte The BOOK_NOT_IN_MANIFEST = 'Book not in manifest' and REPO_NOT_FOUND = 'Repo not found' could be that the user just hasn't created that resource for that book yet, or hasn't created that resource in any BP yet. So it's a status but not really an error. We don't want users to just create things because they think they should all be errorless. What about just an empty circle icon? Or just a blank status? 

Also Looking at the mockup I'm wondering if the statuses are too long for a high level dashboard.  We want more of an engine light and when they hover over it or click it they can get the longer status. 
![image](https://user-images.githubusercontent.com/10272744/146937226-d766e7b0-1733-4c93-ae58-696bc781b184.png)

**Comment by mandolyte** [comment]
@birchamp in the demo, we had feedback indicating a desire to know more, not less. I was asked if a hover over message could be shown on the status to give them "the bigger picture"... not sure exactly what they meant by that...

I was thinking that the "dashboard" (engine light) would be on the TreeItem component, where it says "Resources". These can be styled to add icons, color, etc. In other words, they shouldn't have to open resource details just to get a sense of the health of the book package.

I took a stab at writing the "rules" to determine what shows on the "dashboard", but I need to make updates based this and other insights you have provided. See the issue on the dashboard feature for more...

@birchamp
