### ISSUE TITLE
Remove language specific validation errors

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#81]
Language specific, punctuation and grammar errors should not be included in validation.

**Comment by mandolyte** [comment]
Duplicate of #69

**Comment by mandolyte** [comment]
I plan to do this without actually changing how the uw-content-validation package works. There is a cvFilter() function that is used to suppress certain rows. I will add some logic to this function to exclude Spanish punctuation notices. 

Probably not a long term fix, since non-Latin scripts may cause even more issues. Which may necessitate an overhaul to how CV works.

@birchamp

**Comment by birchamp** [comment]
I like this as a mid term fix
