### ISSUE TITLE
Add hover for fetch error to show what error occurred on what file

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#83]
In the demo we saw a repo with a very informative X files missing error and a fetch error.  Can we get any more informative on the fetch error?  Add hover over to icon to show what the error is and file name.

**Comment by mandolyte** [comment]
I am no long seeing this error in the es-419_gl org. After some search, I found it in the vi_gl org. But only for the OBS resources. Here is a picture:
![image](https://user-images.githubusercontent.com/1289437/153216416-1378a525-f53c-4080-be82-0553d1426775.png)

**Comment by mandolyte** [comment]
Here is the problem:
- In the picture above, the repo `vi_obs-tn` is marked as "ok". However, that repo is still in the old and unsupported markdown format.
- The fetch error is because gA only supports the TSV format and it goes for `tn_OBS.tsv` and does not find it.

I propose we mark the `vi_obs-tn` repo status with a message to convert to TSV. Then the fetch error will go away and will state instead "See TN error"

**Comment by mandolyte** [comment]
Using a positive assertion approach, look for the expected filename. Examples:
tq (fex: path: './gen' and should be tq_GEN.tsv)
sq (should be sq_TIT.tsv)
sn (should be sn_TIT.tsv)


obs-tn (should be tn_OBS.tsv)
obs-tq (should be tq_OBS.tsv)


obs-sq (should be sq_OBS.tsv)
obs-sn (should be sn_OBS.tsv)

**Comment by mandolyte** [comment]
With the above special handling, here is org unfoldingWord and language French for OBS:
![image](https://user-images.githubusercontent.com/1289437/153291930-2a4462eb-1dca-4660-96b0-c4370400c92c.png)

@birchamp this has 4 repos that are in markdown and should be TSV. Notice the new status message "Must be TSV Format"

And for es-419, the TQ resource now returns that message instead of going into an infinite spinner condition.
![image](https://user-images.githubusercontent.com/1289437/153292954-3bec7507-42da-422f-b18a-f3fdf85cc815.png)
